### ISSUE TITLE
mutli user support

### ISSUE THREAD

**Issue by fantastory** [DirtyUnicorns/android_frameworks_base#10]
ld it be possible to support multiuer android feature?
as in:
https://source.android.com/devices/tech/admin/multi-user

**Comment by nychitman1** [comment]
This is supported out of the box in AOSP.

**Comment by fantastory** [comment]
Yes but as I look at:
https://github.com/DirtyUnicorns/android_frameworks_base/blob/p9x/core/res/res/values/config.xml

it is not turned on in dirtyunicorns:
```
    <!--  Maximum number of supported users -->
    <integer name="config_multiuserMaximumUsers">1</integer>

    <!-- Maximum number of users we allow to be running at a time -->
    <integer name="config_multiuserMaxRunningUsers">3</integer>

    <!-- Whether UI for multi user should be shown -->
    <bool name="config_enableMultiUserUI">false</bool>
```

**Comment by timocapa** [comment]
It works fine.

![image](https://user-images.githubusercontent.com/22844613/58026236-4c3bdf80-7b16-11e9-85a4-f8ce4ca81b95.png)

**Comment by nychitman1** [comment]
Clearly, you haven't even tried to use it lol. Locking this conversation.
