### ISSUE TITLE
Alex is a stupid nigger

### ISSUE THREAD

**Issue by PDWarrior** [DirtyUnicorns/android_frameworks_base#11]
https://youtu.be/zOY5Mz6aQbc

![IMG_20200211_231746_167](https://user-images.githubusercontent.com/61384800/75114801-473e2a80-566a-11ea-8cd5-18fa940ecee4.jpg)

**Comment by Genkzsz11** [comment]
@PDWarrior wtf

**Comment by 4PERTURE** [comment]
For the sake of mankind, please delete your GitHub account.

**Comment by uditkarode** [comment]
Why, just why

**Comment by Lyceris-chan** [comment]
OwO
